### ISSUE TITLE
ThreadPoolExecutor methods invocation

### ISSUE THREAD

**Issue by Glebuar** [Glebuar/Percolation#1]
What is the best way to invoke 
```
getPoolSize();
getMaximumPoolSize();
getTaskCount();
```
from main()?
Thanks.

**Comment by b0noI** [comment]
@Glebuar depends on the task, what information you need to get:)? and what you want to do with the information?

**Comment by Glebuar** [comment]
Same as were in #https://github.com/Glebuar/Percolation/commit/154177cc0ce3223d5b51c66bec6a5e3b9367f811
I need to print information about `Current threads in pool` and `Total number of threads`.

**Comment by b0noI** [comment]
In your case, you have pool with the FIXED number of threads and you setting number manually:

```java
Executors.newFixedThreadPool(12);
```

therefore answer on these 2 questions (Current threads in pool and Total number of threads) is 12

**Comment by b0noI** [comment]
However amount of tasks might be different, since tasks been submitted along the way.

**Comment by Glebuar** [comment]
getTaskCout() method is used to show how many tasks you have sent to the executor. So, i'm interesting how i can invoke this from my code.
